version: '3'

services:

  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    restart: "always"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env

